name: Discord bot hosting

on:
  push:
    branches:
      - main

jobs:
  host:
    name: Host
    runs-on: self-hosted
    steps:
    - name: Create and start virtual environment
      run: |
        python -m venv venv
        source venv/Scripts/activate

    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt

    - name: Run the app
      run: |
        python -Om Spoyt
